// Generated by https://pagedraw.io/pages/13415
import React from 'react';
import './webframeevents.css';


export default class Webframeevents extends React.Component {
  render() {
    return (
      <div className="webframeevents-webframeevents-0">
          <div className="webframeevents-0">
              <div className="webframeevents-rectangle-0">
                  <div className="webframeevents-0-0-0">
                      <div className="webframeevents-events-0">Events</div>
                  </div>
              </div>
          </div>
          <div className="webframeevents-1">
              <div className="webframeevents-1-0">
                  <div className="webframeevents-1-0-0">
                      <div className="webframeevents-1-0-0-0">
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/97fb/30e3/9d96196f365d9a61f2a0865de697b0cf" className="webframeevents-image-5" /> 
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/25b3/3bae/1ce52a449e6cb04871671f3fef4d539c" className="webframeevents-image-6" /> 
                          <div className="webframeevents-wells_fargo_center_4">
                              <br/>
                              <div>{"Date: 10/20/2018"}</div>
                              <div>{"Cost: Free"}</div>
                              <div>{"Time: 11:00am - 7:00pm"}</div>
                              <br/>
                              <div>Wells Fargo Center</div>
                              <div>456 West Avenue Pavilion</div>
                              <div>Charlotte, NC 28209</div>
                              <br/>
                              <div>The 5th annual Charlotte Brewing Fair is back in town along with a variety of beloved and new food and beverage vendors. TART will have a booth in the southwest corner of the grounds and will be offering its traditional tap list and unveiling a new brew!</div>
                          </div>
                          <div className="webframeevents-oakleaf_orchard_6">
                              <br/>
                              <div>{"Date: 10/30/2018"}</div>
                              <div>{"Cost: 35.00"}</div>
                              <div>{"Time: 11:00am -6:00pm"}</div>
                              <br/>
                              <div>Oakleaf Orchard</div>
                              <div>6789 Old Orchard Road</div>
                              <div>Fort Mill, SC 29715</div>
                              <br/>
                              <div>Oakleaf Orchard is celebrating all things Autumn and alcoholic with a plethora of cider, mead, and beer vendors offering samples all day long. The single entry fee covers one Autumn at the Orchard glass and unlimited samples!</div>
                          </div>
                          <div className="webframeevents-rectangle_2" /> 
                          <div className="webframeevents-charlotte_brewing_fair_-8">
                              Charlotte Brewing Fair
                          </div>
                          <div className="webframeevents-autumn_at_the_orchard_-7">
                              Autumn at the Orchard
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="webframeevents-2" /> 
      </div>
    );
  }
};
