// Generated by https://pagedraw.io/pages/13415
import React from 'react';
import './webframehome.css';


export default class Webframehome extends React.Component {
  render() {
    return (
      <div className="webframehome-webframehome-0">
          <div className="webframehome-0">
              <div className="webframehome-image-6">
                  <div className="webframehome-0-0-0">
                      <div className="webframehome-0-0-0-0">
                          <div className="webframehome-october_2">
                              <div>October 20th, 2018</div>
                              <div>Charlotte Brewing Fair</div>
                              <br/>
                              <br/>
                              <br/>
                          </div>
                          <div className="webframehome-rectangle_3" /> 
                          <div className="webframehome-experience_a_variety_of_brews_ciders_and_meads_and_visit_our_booth_where_tart_will_unveil_a_new_autumn_cider_-0">
                              Experience a variety of brews, ciders, and meads and visit our booth where TART will unveil a new autumn cider!
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="webframehome-1" /> 
      </div>
    );
  }
};
